opium_api:
    type: rest
    resource: "@OpiumBundle/Resources/config/routing/api.yml"
    prefix:   /v1

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

opium_image:
    resource: "@OpiumPhotoBundle/Resources/config/image.yml"
    prefix:   /
