security:
    providers:
        in_memory:
            memory: 
                users: %users%

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: false
            http_basic:
                realm: "Opium secured area"

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
