security:
    providers:
        in_memory:
            memory: 
                users: %users%

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/v[1-9][0-9]?/
            anonymous: true
            http_basic:
                realm: "Opium secured area"

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { methods: OPTIONS, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { role: IS_AUTHENTICATED_FULLY }
