security:
    providers:
        in_memory:
            memory: 
                users: %users%

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/v[1-9][0-9]?/
            anonymous: false
            http_basic:
                realm: "Opium secured area"

    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: "bcrypt"
            cost: 14

    access_control:
        - { methods: OPTIONS, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { role: ROLE_USER }
