image_crop:
    path:  "/{path}/thumbs/{width}-{height}.{extension}"
    defaults: 
        _controller: OpiumPhotoBundle:File:cropImage
    requirements:
        path: .+
        _method: GET

basefile:
    path:  "/{path}"
    defaults: 
        _controller: OpiumPhotoBundle:File:baseFile
    requirements:
        path: "|.+"
        _method: GET

