#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

opium_options:
    methods: [OPTIONS]
    path: /{anything}
    defaults:
        _controller: FrameworkBundle:Template:template
        template: empty.html.twig
        maxAge: 86400
        sharedMaxAge: 86400
    requirements:
        anything: ".*"

