opium_photo:
    path:  "/{path}/{photo}"
    defaults: 
        _controller: OpiumBundle:Directory:photo
    requirements:
        path: "|.+"
        photo: "[^/]+"
        _method: GET

opium_directory:
    path:  "/{path}/"
    defaults: 
        _controller: OpiumBundle:Directory:index
    requirements:
        path: "|.+"
        _method: GET

opium_directory_update:
    path:  "/{path}/"
    defaults: 
        _controller: OpiumBundle:Directory:update
    requirements:
        path: "|.+"
        _method: POST
