#opium.api.photo:
#    path:  "/{path}/{photo}"
#    defaults: 
#        _controller: OpiumBundle:Directory:photo
#    requirements:
#        path: "|.+"
#        photo: "[^/]+"
#        _method: GET

api.directories:
    type: rest
    resource: "OpiumBundle:Directory"
    name_prefix: opium_api_

api.files:
    type: rest
    resource: "OpiumBundle:File"
    name_prefix: opium_api_

api.users:
    type: rest
    resource: "OpiumBundle:User"
    name_prefix: opium_api_

#opium_directory_update:
#    path:  "/{path}/"
#    defaults: 
#        _controller: OpiumBundle:Directory:update
#    requirements:
#        path: "|.+"
#        _method: POST
