image_crop:
    path:  "/{path}/thumbs/{width}-{height}.{extension}"
    defaults: 
        _controller: OpiumBundle:File:cropImage
    requirements:
        path: .+
        width: "[0-9]*"
        height: "[0-9]*"
        _method: GET

basefile:
    path:  "/{path}"
    defaults: 
        _controller: OpiumBundle:File:baseFile
    requirements:
        path: "|.+"
        _method: GET

