Opium\OpiumBundle\Entity\Photo:
    type: entity
    extends: File

    fields:
        displayable:
            type: boolean
            nullable: false

        exif:
            type: json_array
            nullable: true

