Opium\OpiumBundle\Entity\Directory:
    properties:
        children:
            expose: true
            access_type: public_method
            read_only: true
            type: array
            max_depth: 1

        directoryThumbnail:
            type: Opium\OpiumBundle\Entity\Photo

    relations:
        -
            rel: self
            href:
                route: "opium_api_get_directory"
                parameters: 
                    path: "expr(object.getId())"
            exclusion:
                exclude_if: "expr(object.getPathname() == '/')"

        -
            rel: self
            href:
                route: "opium_api_get_directories"
            exclusion:
                exclude_if: "expr(object.getPathname() != '/')"
