Opium\OpiumBundle\Entity\File:
    properties:
        finder: { exclude: true }

        parent:
            access_type: public_method
            read_only: true
            max_depth: 1

    virtual_properties:
        getId:
            serialized_name: id
            type: string

        getType:
            serialized_name: type
            type: string

    relations:
        -
            rel: parent
            href:
                route: "opium_api_get_directory"
                parameters: 
                    path: "expr(object.getParent().getId())"
            exclusion:
                exclude_if: "expr(!object.getParentPath())"

        -
            rel: parent
            href:
                route: "opium_api_get_directories"
            exclusion:
                exclude_if: "expr(object.getParentPath() || object.getPathname() == '/')"
