Opium\OpiumBundle\Entity\Directory:
    exclusion_policy: all
    virtual_properties:
        #directoryThumbnail:
        #    expose: true
        #    type: Opium\OpiumBundle\Entity\Photo

        getDisplayableChildren:
            serialized_name: "children"
            type: array
            max_depth: 2

    relations:
        -
            rel: self
            href:
                route: "opium_api_get_directory"
                absolute: true
                parameters: 
                    path: "expr(object.getId())"
            exclusion:
                exclude_if: "expr(object.getName())"

        -
            rel: self
            href:
                route: "opium_api_get_directories"
                absolute: true
            exclusion:
                exclude_if: "expr(!object.getName())"

        -
            rel: directory_thumbnail
            embedded: "expr(object.getDirectoryThumbnail())"

        #-
        #    rel: children
        #    embedded: 
        #        content: "expr(object.getChildren())"
        #        exclusion: 
        #            maxDepth: 1
        #            max_depth: 1
        #    exclusion: 
        #        maxDepth: 1
        #        max_depth: 1

