Opium\OpiumBundle\Entity\Photo: 
    properties:
        image:
            type: array


    relations:
        -
            rel: self
            href:
                route: opium_api_get_file
                parameters:
                    path: "expr(object.getId())"

