App\Entity\File:
    type: entity
    table: file
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: dtype
        type: string
    discriminatorMap:
        directory: App\Entity\Directory
        photo: App\Entity\Photo

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        pathname:
            type: string
            length: 255

        name:
            type: string
            length: 100

        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    fields:
                        - name

    manyToOne:
        parent:
            targetEntity: Directory
            inversedBy: children

    lifecycleCallbacks:
        prePersist: [ prePersist ]
